---
title: '1.13 defer, panic, recovery'
slug: go-defer-panic-recovery
weight: 1013
---

## 1.13.1 تعویق (defer)

کلمه کلیدی defer یکی از کاربردی ترین امکانات زبان گو را برای ما فراهم میسازد. شما می توانید اجرای یک تابع را به تعویق بندازید‍‍. عموما defer برای توابعی کاربرد دارد که قصد پاکسازی یا بستن عملیات های صورت گرفته را دارند, نظیر توابع Close در برخی از جاها.

 ![defer](../../assets/img/content/chapter1/defer-panic-recovery/1.png)

به مثال زیر توجه کنید:
```go
package main

import (
	"fmt"
)

func main() {
	defer fmt.Println("world")
	fmt.Println("hello")
}
```

```shell
$ go run main.go
hello
world
```


### 1.13.1.1 تعویق (defer) در توابع (Anonymous)

شما خیلی ساده می توانید با استفاده از توابع `Anonymous` `توابع بینام یا گمنام :)` اجرای قسمتی از برنامه خودتون رو به تعویق بندازین. به مثال زیر توجه کنید :

```go
package main

import "fmt"

func main() {
    defer func() { fmt.Println("In inline defer") }()
    fmt.Println("Executed")
}
```

```shell
$ go run main.go
Executed
In inline defer
```
به این نکته توجه کنید که `defer` قبل از `return` صدا زده میشود. یعنی قبل از اینکه تابع شما خروجی را برگشت بدهد `اگه تابع خروجی داشته باشه` **defer** اجرا خواهد شد.

### 1.13.1.2 تعویق (defer) چندین تابع درون یک تابع

در کد زیر, ما داخل یک تابع چند تابع را با استفاده از (defer) به تعویق انداختیم. به مثال زیر توجه کنید:

```go
package main
import "fmt"
func main() {
    i := 0
    i = 1
    defer fmt.Println(i)
    i = 2
    defer fmt.Println(i)
    i = 3
    defer fmt.Println(i)
}
```

```shell
$ go run main.go
3
2
1
```
**دقت داشته باشید که مقداردهی پارامترهای ورودی, برای تابعی که آن را defer کردیم در همان لحظه call شدن آن انجام میشود. به مثال زیر توجه کنید:**
```shell
package main

import "fmt"

func main() {
	i:=1
	defer fmt.Println(i)
	i++
	fmt.Println(i)
	fmt.Println("First")
}
```

```shell
$ go run main.go
2
First
1
```
در این مرحله شما باید پی برده باشید که **defer** در همان خطی که نوشته شده است صدا زده میشود, ولی اجرای آن دقیقا به قبل از **return** در تابع موکول میشود.

## 1.13.2 پنیک (panic)

در زبان گو panic همانند exception به معنای خروج از برنامه در شرایط غیر عادی می باشد. panic در ۲ حالت زیر پیش می آید:

- خطاهای  {{< tooltip text="در زمان اجرای" note="runtime" >}} برنامه
- فراخوانی تابع panic توسط برنامه نویس در بخش های مختلف برنامه

```go
func panic(v interface{})
```

شما میتوانید با استفاده از تابع فوق که در توابع `built-in` گولنگ وجود دارد, panic ایجاد کنید و به عنوان ورودی دلیل panic را در قالب یک رشته به تابع ارسال کنید.


{{< hint info >}}
تایپ `{}interface` یک تایپ بسیار کاربردی است. ما از این تایپ مواقعی استفاده میکنیم که نمیدانیم ورودی تابع چه خواهد بود. به مثال زیر توجه کنید:

```go
package main

import "fmt"

var (
	a interface{} = 123
	b interface{} = "abcd"
	c interface{} = 2.5
)

func main() {
	fmt.Printf("%v, %T\n", a, a)
	fmt.Printf("%v, %T\n", b, b)
	fmt.Printf("%v, %T\n", c, c)
}
```

```shell
$ go run main.go
123, int
abcd, string
2.5, float64
```

همونطور که در مثال بالا دیدید, ما به تایپ `interface` چندین نوع دیتا تایپ رو دادیم و خود کامپایلر زبان گو متوجه نوع اون تایپ ها شد. در فصل بعدی بیشتر با تایپ ها آشنا خواهید شد.
{{< /hint >}}

### 1.13.2.1 خطای panic در زمان اجرا (runtime)

خطاهای panic در زمان اجرا به دلایل زیر می تواند رخ دهد :
- خطای Out of bounds/range array/slice
- فراخوانی متغیری که nil pointer باشد `یعنی به هیچ آدرسی از حافظه ` **memory** `اشاره نمیکند`
- ارسال داده برروی کانال های بسته شده
- type assertion نادرست



```go
package main

import "fmt"

func main() {

	a := []string{"a", "b"}
	print(a, 2)
}

func print(a []string, index int) {
	fmt.Println(a[index])
}
```

```shell
$ go run main.go
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.checkAndPrint(...)
        main.go:12
main.main()
        /main.go:8 +0x1b
exit status 2
```

در تابع فوق ما یک تابع نوشتیم که به عنوان ورودی یک اسلایس از نوع رشته و یک ایندکس از نوع عدد از ما دریافت میکند و المنت **ایندکسم**‌ اون اسلایس را برای ما چاپ میکند `در مثال بالا یعنی اندیس شماره 2`. این کار ما باعث بروز یک **panic** میشود, فکر میکنید به چه دلیل ؟ بله به این دلیل که اسلایس ما اندیس شماره 2 ندارد و دلیل آن هم این است که اسلایس, لیست و .... از 0 شروع میشوند.

پنیک یک سری اطلاعات در مورد چرایی بوجود امدنش به ما میدهد که در ادامه آنهارو توضیح دادیم:
- پنیک رخ داده شامل متن خطا
- محل رخ دادن panic در قالب stacktrace


### 1.13.2.2 خطای panic از قبل تعیین شده توسط برنامه نویس

همانطور که گفتیم شما می توانید هرجایی از بدنه توابع خود, تابع panic را فراخوانی کنید **البته این روش پیشنهاد نمیشود و روش پیشنهادی استفاده از شیوه ی ارور هندلینگ خود گولنگ است و فقط در صورت لزوم بهتر است از پنیک استفاده شود. همینطور شما باید در داکیومنت برنامه ذکر کنید که کدام قسمت برنامه امکان پنیک را دارد تا دیگران بتوانند در صورت لزوم آن را recover کنند. recover را در ادمه توضیح خواهم داد.** تا برنامه در آن محل خطایی را نمایش داده و متوقف شود.

```go
package main

import "fmt"

func main() {

	a := []string{"a", "b"}
	checkAndPrint(a, 2)
}

func checkAndPrint(a []string, index int) {
	if index > (len(a) - 1) {
		panic("Out of bound access for slice")
	}
	fmt.Println(a[index])
}
```

```shell
$ go run main.go
panic: Out of bound access for slice

goroutine 1 [running]:
main.checkAndPrint(0xc000104f58, 0x2, 0x2, 0x2)
      main.go:13 +0xe2
main.main()
        main.go:8 +0x7d
exit status 2
```

{{< hint info >}}
توجه کنید استفاده از تابع panic در برخی مواقع مفید می باشد. به عنوان مثال قصد دارید هنگام اجرای برنامه, یکسری تنظیمات از سمت کاربر دریافت کنید و در صورتیکه تنظیمات دارای مشکل بودند, می توانید با استفاده panic جلوی ادامه روند برنامه را بگیرید تا کاربر خطا را رفع کند.
{{< /hint >}}

## 1.13.3 بازیابی (recovery)

برخی اوقات panic ها غیرقابل پیش بینی میشوند. ممکن است برنامه شما بدون هیچ خطایی اجرا شود و به روند خود ادامه دهد, اما این هم ممکن است که به یک دلیل نامعلوم یا بهتر است بگوییم پیش بینی نشده, panic رخ دهد و برنامه شما کاملا متوقف و باعث از دست دادن وضعیت استیبل برنامه شود.

به همین منظور در گولنگ یک تابع به نام `recover` وجود دارد که پس از رخ دادن panic در برنامه, این قابلیت را به ما میدهد تا بتوانیم برنامه را به وضعیت قبلی خود بازگردانیم تا بعدا خطای panic رخ داده را بررسی و رفع کنیم.

```go
func recover() interface{}
```

همینطور که شما هم میبینید, تابع ریکاور هیچ ورودی ای نمیگیرد و یک خروجی از تایپ `interface` را برمیگرداند.

به مثالی که در مورد تابع **recover** زدیم نگاه کنید:

```go
package main

import "fmt"

func main() {

	a := []string{"a", "b"}
	checkAndPrint(a, 2)
	fmt.Println("Exiting normally")
}

func checkAndPrint(a []string, index int) {
	defer handleOutOfBounds()
	if index > (len(a) - 1) {
		panic("Out of bound access for slice")
	}
	fmt.Println(a[index])
}

func handleOutOfBounds() {
	if r := recover(); r != nil {
		fmt.Println("Recovering from panic:", r)
	}
}
```

```shell
$ go run main.go
Recovering from panic: Out of bound access for slice
Exiting normally
```

در کد فوق ما یک تابع داریم که در این تابع یک المنت از یک اسلایس را چاپ می کند, اما اگر این اندیس خارج از تعداد المنت های اسلایس باشد یک خطای panic رخ می دهد.
ما برای جلوگیری از خطای panic  تابع handleOutOfBounds را با استفاده defer درون تابع checkAndPrint قرار دادیم که پس از رخ دادن panic بصورت خودکار بازیابی صورت بگیرد تا برنامه ما متوقف نشود.

## 1.13.4 چاپ اطلاعات stacktrace پس از بازیابی

شما می توانید پس از اینکه بازیابی را انجام دادید, جزئیات بیشتری در خصوص خطای panic رخ داده بدست آوردید. به مثال زیر توجه کنید:

```go
package main
import (
    "fmt"
    "runtime/debug"
)
func main() {
    a := []string{"a", "b"}
    checkAndPrint(a, 2)
    fmt.Println("Exiting normally")
}
func checkAndPrint(a []string, index int) {
    defer handleOutOfBounds()
    if index > (len(a) - 1) {
        panic("Out of bound access for slice")
    }
    fmt.Println(a[index])
}
func handleOutOfBounds() {
    if r := recover(); r != nil {
        fmt.Println("Recovering from panic:", r)
        fmt.Println("Stack Trace:")
        debug.PrintStack()
    }
}
```

```shell
$ go run main.go
Recovering from panic: Out of bound access for slice
Stack Trace:
goroutine 1 [running]:
runtime/debug.Stack(0xd, 0x0, 0x0)
        stack.go:24 +0x9d
runtime/debug.PrintStack()
        stack.go:16 +0x22
main.handleOutOfBounds()
        main.go:27 +0x10f
panic(0x10ab8c0, 0x10e8f60)
        /Users/slohia/Documents/goversion/go1.14.1/src/runtime/panic.go:967 +0x166
main.checkAndPrint(0xc000104f58, 0x2, 0x2, 0x2)
        main.go:18 +0x111
main.main()
        main.go:11 +0x81
Exiting normally
```

**برای چاپ اطلاعات stacktrace همانطور که میبینید ما از پکیج runtime که در کتابخانه استاندارد گولنگ وجود دارد استفاده کردیم**

